//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextExtractorGUI.Ressources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TextExtractorGUI.Ressources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string Header_Title {
            get {
                return ResourceManager.GetString("Header_Title", resourceCulture);
            }
        }
        
        internal static string Header_Subtitle {
            get {
                return ResourceManager.GetString("Header_Subtitle", resourceCulture);
            }
        }
        
        internal static string Input_Header {
            get {
                return ResourceManager.GetString("Input_Header", resourceCulture);
            }
        }
        
        internal static string Input_Watermark {
            get {
                return ResourceManager.GetString("Input_Watermark", resourceCulture);
            }
        }
        
        internal static string Input_Browse {
            get {
                return ResourceManager.GetString("Input_Browse", resourceCulture);
            }
        }
        
        internal static string Output_Header {
            get {
                return ResourceManager.GetString("Output_Header", resourceCulture);
            }
        }
        
        internal static string Output_Watermark {
            get {
                return ResourceManager.GetString("Output_Watermark", resourceCulture);
            }
        }
        
        internal static string Output_SaveAs {
            get {
                return ResourceManager.GetString("Output_SaveAs", resourceCulture);
            }
        }
        
        internal static string Action_Extract {
            get {
                return ResourceManager.GetString("Action_Extract", resourceCulture);
            }
        }
        
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
        
        internal static string Status_Extracting {
            get {
                return ResourceManager.GetString("Status_Extracting", resourceCulture);
            }
        }
        
        internal static string Error_SelectIndexHtml {
            get {
                return ResourceManager.GetString("Error_SelectIndexHtml", resourceCulture);
            }
        }
        
        internal static string Error_SelectMarkdownTarget {
            get {
                return ResourceManager.GetString("Error_SelectMarkdownTarget", resourceCulture);
            }
        }
        
        internal static string Error_Unexpected {
            get {
                return ResourceManager.GetString("Error_Unexpected", resourceCulture);
            }
        }
        
        internal static string Result_Success {
            get {
                return ResourceManager.GetString("Result_Success", resourceCulture);
            }
        }
        
        internal static string Result_EndedWithCode {
            get {
                return ResourceManager.GetString("Result_EndedWithCode", resourceCulture);
            }
        }
        
        internal static string Label_Log {
            get {
                return ResourceManager.GetString("Label_Log", resourceCulture);
            }
        }
        
        internal static string Label_Error {
            get {
                return ResourceManager.GetString("Label_Error", resourceCulture);
            }
        }
        
        internal static string Notes_Name {
            get {
                return ResourceManager.GetString("Notes_Name", resourceCulture);
            }
        }
        
        internal static string Select_IndexHtml {
            get {
                return ResourceManager.GetString("Select_IndexHtml", resourceCulture);
            }
        }
        
        internal static string Select_MarkdownOutputPath {
            get {
                return ResourceManager.GetString("Select_MarkdownOutputPath", resourceCulture);
            }
        }
        
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        internal static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        internal static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        internal static string Settings_Close {
            get {
                return ResourceManager.GetString("Settings_Close", resourceCulture);
            }
        }
    }
}
